pre_bump_hooks = [
    "echo {{version}}",
]

post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "server"
owner = "coldrune"
authors = [
  { username = "muratgozel", signature = "Murat Gözel"}
]
