core:
  debug: "${DEBUG:1}"
server_gateways:
  pg_conn_str: "${PG_CONN_STR}"
  postmark_server_token: "${POSTMARK_SERVER_TOKEN}"
  postmark_from: "Deployment Server Testing <os-testing@gozel.com.tr>"
  rabbitmq_conn_str: "${RABBITMQ_CONN_STR}"
  github_webhook_secret_token: "${GITHUB_WEBHOOK_SECRET_TOKEN}"
server:
  api_user: "${API_USER}"
  api_secret: "${API_SECRET}"